[platformio]
default_envs = m5stack-cores3

[env]
platform = espressif32 @ 6.5.0
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.filesystem = spiffs
board_build.partitions = default_16MB.csv
build_flags = -DCORE_DEBUG_LEVEL=3
lib_deps =
  m5stack/M5Unified@0.1.16
  stack-chan/stackchan-arduino
  bblanchon/ArduinoJson@^7.0.0
lib_ldf_mode = deep

[env:m5stack-cores3]
board = m5stack-cores3
