[platformio]
default_envs = m5stick-c-plus

[env]
platform = espressif32 @ 6.5.0
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -std=gnu++14
lib_deps =
  m5stack/M5Unified@0.1.16

; M5StickC Plus (ESP32-PICO-D4, MPU6886 IMU)
[env:m5stick-c-plus]
board = m5stick-c-plus

; M5StickC Plus2 variant
; [env:m5stick-c-plus2]
; board = m5stick-c-plus2
